import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={`fa`} dir={`rtl`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className={`
    
      fixed top-0 left-0 right-0 z-50 transition-all duration-300 bg-gray-900 text-white`}>
          Full-Stack Digital Brandscapes
          | Design &
          Development TEAMS |
          SaaS Expertise |
          Brand Systems |
          <h1>The artist operates from the deepest stratum—aware that each gesture carries the weight of every prior grounding. To create now is to create within the entire history.</h1>
      </header>
      <div className={`flex `}>
        {/*<SideNavIconic/>*/}
        {/*  <header><RemoteDevCard/></header>*/}
      </div>
        {children}

      --------------
      محتوای پرچم‌دار
      محتوای تحلیلی و پرچم‌دار
      مقالات، تحلیل‌ها و گزارش‌های عمیق درباره بازار کار، سازمان‌های یادگیرنده و آینده استعدادیابی

      مقالات ویژه
      مقالات اصلی و پرمخاطب
      تحلیل بازار کار
      چرا LinkedIn دیگر کافی نیست؟
      بررسی محدودیت‌های ساختاری پلتفرم‌های استخدامی سنتی در بازنمایی استعدادهای واقعی و چگونگی پیدایش شکاف‌های عمیق در بازار کار مدرن

      ۱۴۰۳/۱۱/۲۳
      ۱۲ دقیقه
      مطالعه

      </body>
    </html>
  );
}
