import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNavIconic from "@/app/private/(layout)/SideNavIconic";
import RemoteDevCard from "@/app/remoteDevCard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={`fa`} dir={`rtl`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className={`flex `}>
        <SideNavIconic/>
          <header><RemoteDevCard/></header>
      </div>
        {children}
      محتوای پرچم‌دار
      محتوای تحلیلی و پرچم‌دار
      مقالات، تحلیل‌ها و گزارش‌های عمیق درباره بازار کار، سازمان‌های یادگیرنده و آینده استعدادیابی

      مقالات ویژه
      مقالات اصلی و پرمخاطب
      تحلیل بازار کار
      چرا LinkedIn دیگر کافی نیست؟
      بررسی محدودیت‌های ساختاری پلتفرم‌های استخدامی سنتی در بازنمایی استعدادهای واقعی و چگونگی پیدایش شکاف‌های عمیق در بازار کار مدرن

      ۱۴۰۳/۱۱/۲۳
      ۱۲ دقیقه
      مطالعه

      </body>
    </html>
  );
}
